In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as ns

In [3]:
import numpy as ns
arr=ns.array([1,2,3,4,5,6,7])
print(arr)                              # Creating arrays with numpy and accesing the single array
print(arr[3])

[1 2 3 4 5 6 7]
4


In [5]:
import numpy as ns
arr=ns. array([[99,98,97,96,95],
             [6,7,8,9,10]])            # Creating two dimensional arrays using numpy
print(arr)

[[99 98 97 96 95]
 [ 6  7  8  9 10]]


In [7]:
import numpy as ns
arr=ns.array([[[11,12,13,14,15],        # Creating three dimensional arrays using numpy
              [16,17,18,19,20],
              [12,13,14,15,16]]])
print(arr)

[[[11 12 13 14 15]
  [16 17 18 19 20]
  [12 13 14 15 16]]]


In [8]:
import numpy as ns
arr=ns.array([11,12,13,14,15,16])          # array addition using numpy
print(arr[2] + arr[5])

29


In [9]:
import numpy as ns
arr=ns.array([[15,16,17],
             [18,19,20],
             [21,22,23],                        # Accesing the two dimensional array 
             [24,25,26],
             [27,28,29]])
print("4th row in 3rd element,arr:",arr[3,2])
print("2nd row in 2nd element,arr:",arr[1,2])

4th row in 3rd element,arr: 26
2nd row in 2nd element,arr: 20


In [10]:
import numpy as ns
arr=ns.array([[[11,12,13,14],
              [15,16,17,18]],
              
             [[19,20,21,22],
             [23,24,25,26]],
              
              [[27,28,29,30],
              [31,32,33,34]],                            # Creating 3d arrays using numpy
              
              [[35,36,37,38],
              [39,40,41,42]],
              
              [[43,44,45,46],
              [47,48,49,50]],
              
              [[51,52,53,54],
              [55,56,57,58]]])
print(arr[2,1,3])
print(arr[4,1,2])
print(arr[5,0,3])


34
49
54


In [11]:
import numpy as ns
arr=ns.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24])
newarr=arr.reshape(4,6)
print(newarr)                                          # reshape array using numpy

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [12]:
import numpy as ns
a = ns.array([1,2,3,4,5])
b = ns.array([[6,7,8,9,10],[11,12,13,14,15]])
c = ns.array([[[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]]])    # ndim using numpy
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


In [13]:
from numpy import random
x = random.randint(100,size=(5))
print(x)                                    # random function using numpy
                          

[64 17 75 22 85]
