In [1]:
import numpy as ns
array=ns.array([[[50,51,52,53,54], 
              [26,27,28,29,30]],
              
              [[32,33,34,35,36],
              [38,39,40,41,42]],
              
              [[44,45,46,47,48],
              [50,51,52,53,54]],          # Creating 3D to 2D array
              
              [[56,57,58,59,60],
              [62,63,64,65,66]],
              
              [[68,69,70,71,72],
              [74,75,76,77,78]]])
reshaped_array=ns.reshape(array,(10,5))
print("original array:\n",array)
print("reshaped array:\n",reshaped_array)

original array:
 [[[50 51 52 53 54]
  [26 27 28 29 30]]

 [[32 33 34 35 36]
  [38 39 40 41 42]]

 [[44 45 46 47 48]
  [50 51 52 53 54]]

 [[56 57 58 59 60]
  [62 63 64 65 66]]

 [[68 69 70 71 72]
  [74 75 76 77 78]]]
reshaped array:
 [[50 51 52 53 54]
 [26 27 28 29 30]
 [32 33 34 35 36]
 [38 39 40 41 42]
 [44 45 46 47 48]
 [50 51 52 53 54]
 [56 57 58 59 60]
 [62 63 64 65 66]
 [68 69 70 71 72]
 [74 75 76 77 78]]


In [2]:
import numpy as ns
array=ns.array([10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36])
newarray=array.reshape(3,3,3)
print(newarray)                             # Creating 1D to 3D array

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]
